### ISSUE TITLE
gem should call out `eventmachine` dependency

### ISSUE THREAD

**Issue by benmullin333** [signalfx/signalfx-ruby#20]
using this gem outside of Rails yields this message... 
workaround is to include `eventmachine` in my own project

```
/Users/benmullin/.rvm/gems/ruby-2.2.2/gems/signalfx-2.0.1/lib/signalfx/signalflow/websocket.rb:6:in `require': cannot load such file -- eventmachine (LoadError)
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/gems/signalfx-2.0.1/lib/signalfx/signalflow/websocket.rb:6:in `<top (required)>'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/gems/signalfx-2.0.1/lib/signalfx/signalflow/client.rb:5:in `require_relative'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/gems/signalfx-2.0.1/lib/signalfx/signalflow/client.rb:5:in `<top (required)>'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/gems/signalfx-2.0.1/lib/signalfx/signal_fx_client.rb:5:in `require_relative'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/gems/signalfx-2.0.1/lib/signalfx/signal_fx_client.rb:5:in `<top (required)>'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/gems/signalfx-2.0.1/lib/signalfx/protobuf_signal_fx_client.rb:5:in `require_relative'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/gems/signalfx-2.0.1/lib/signalfx/protobuf_signal_fx_client.rb:5:in `<top (required)>'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/gems/signalfx-2.0.1/lib/signalfx.rb:4:in `require_relative'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/gems/signalfx-2.0.1/lib/signalfx.rb:4:in `<top (required)>'
	from /Users/benmullin/Workspace/devops_chef/.chef/plugins/knife/change_deploy_times.rb:2:in `require'
	from /Users/benmullin/Workspace/devops_chef/.chef/plugins/knife/change_deploy_times.rb:2:in `<top (required)>'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/gems/chef-12.9.38/lib/chef/knife/core/subcommand_loader.rb:100:in `load'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/gems/chef-12.9.38/lib/chef/knife/core/subcommand_loader.rb:100:in `block in load_commands'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/gems/chef-12.9.38/lib/chef/knife/core/subcommand_loader.rb:100:in `each'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/gems/chef-12.9.38/lib/chef/knife/core/subcommand_loader.rb:100:in `load_commands'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/gems/chef-12.9.38/lib/chef/knife/core/subcommand_loader.rb:110:in `load_command'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/gems/chef-12.9.38/lib/chef/knife/core/subcommand_loader.rb:124:in `command_class_from'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/gems/chef-12.9.38/lib/chef/knife.rb:153:in `subcommand_class_from'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/gems/chef-12.9.38/lib/chef/knife.rb:214:in `run'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/gems/chef-12.9.38/lib/chef/application/knife.rb:148:in `run'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/gems/chef-12.9.38/bin/knife:25:in `<top (required)>'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/bin/knife:23:in `load'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/bin/knife:23:in `<main>'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/benmullin/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by mpetazzoni** [comment]
@keitwb Can you take a look when you get a chance and send a PR? We indeed `require 'eventmachine'` in the WebSocket transport implementation of the SignalFlow client. Seems like it's just a matter of adding this to the gemspec file:

`spec.add_dependency 'eventmachine', '~> 1.2.5'`
